CREATE TABLE IF NOT EXISTS perks (
  p_veterancy VARCHAR(100),
  p_perkIndex     INT UNSIGNED NOT NULL,
  p_damageHealed  INT UNSIGNED NOT NULL,
  p_weldingPoints INT UNSIGNED NOT NULL,
  p_shotgunDamage INT UNSIGNED NOT NULL,
  p_headshotKills INT UNSIGNED NOT NULL,
  p_stalkerKills INT UNSIGNED NOT NULL,
  p_bullpupDamage INT UNSIGNED NOT NULL,
  p_meleeDamage INT UNSIGNED NOT NULL,
  p_flamethrowerDamage INT UNSIGNED NOT NULL,
  p_selfHeals INT UNSIGNED NOT NULL,
  p_soleSurvivorWaves INT UNSIGNED NOT NULL,
  p_cashDonated INT UNSIGNED NOT NULL,
  p_feedingKills INT UNSIGNED NOT NULL,
  p_burningCrossbowKills INT UNSIGNED NOT NULL,
  p_gibbedFleshpounds INT UNSIGNED NOT NULL,
  p_stalkersKilledWithExplosives INT UNSIGNED NOT NULL,
  p_gibbedEnemies INT UNSIGNED NOT NULL,
  p_bloatKills INT UNSIGNED NOT NULL,
  p_sirenKills INT UNSIGNED NOT NULL,
  p_kills INT UNSIGNED NOT NULL,
  p_explosivesDamage INT UNSIGNED NOT NULL,
  p_totalZedTime INT UNSIGNED NOT NULL,
  p_totalPlayTime INT UNSIGNED NOT NULL,
  p_wins INT UNSIGNED NOT NULL,
  p_lostCount INT UNSIGNED NOT NULL,
  p_character VARCHAR(50) NOT NULL,
  p_customPerks VARCHAR(500) NOT NULL,
  id INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  steamid32 VARCHAR(50) UNIQUE KEY,
  steamid64 VARCHAR(20) UNIQUE KEY
);