CREATE TABLE IF NOT EXISTS `perks` (
  `p_veterancy` varchar(100) NOT NULL DEFAULT 'SRVetFieldMedic',
  `p_perkIndex` int unsigned NOT NULL,
  `p_damageHealed` int unsigned NOT NULL,
  `p_weldingPoints` int unsigned NOT NULL,
  `p_shotgunDamage` int unsigned NOT NULL,
  `p_headshotKills` int unsigned NOT NULL,
  `p_stalkerKills` int unsigned NOT NULL,
  `p_bullpupDamage` int unsigned NOT NULL,
  `p_meleeDamage` int unsigned NOT NULL,
  `p_flamethrowerDamage` int unsigned NOT NULL,
  `p_selfHeals` int unsigned NOT NULL,
  `p_soleSurvivorWaves` int unsigned NOT NULL,
  `p_cashDonated` int unsigned NOT NULL,
  `p_feedingKills` int unsigned NOT NULL,
  `p_burningCrossbowKills` int unsigned NOT NULL,
  `p_gibbedFleshpounds` int unsigned NOT NULL,
  `p_stalkersKilledWithExplosives` int unsigned NOT NULL,
  `p_gibbedEnemies` int unsigned NOT NULL,
  `p_bloatKills` int unsigned NOT NULL,
  `p_sirenKills` int unsigned NOT NULL,
  `p_kills` int unsigned NOT NULL,
  `p_explosivesDamage` int unsigned NOT NULL,
  `p_totalZedTime` int unsigned NOT NULL,
  `p_totalPlayTime` int unsigned NOT NULL,
  `p_wins` int unsigned NOT NULL,
  `p_lostCount` int unsigned NOT NULL,
  `p_character` varchar(50) NOT NULL DEFAULT '',
  `p_customPerks` varchar(500) NOT NULL DEFAULT '',
  `steamid32` varchar(50) NOT NULL,
  `steamid64` varchar(25) NOT NULL,
  `added` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`steamid32`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;